Repository bob-fornal/100-Days-Of-Code--Tracker, pull requests merged in 2022-10, with the labels that each got.

#6 Save and load JSON
  src/app/app.module.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.scss
  src/app/pages/dashboard/dashboard.component.ts
  src/app/shared/drag-and-drop.directive.spec.ts
  src/app/shared/drag-and-drop.directive.ts
Labels: DASHBOARD

#10 Goals
  src/app/core/constants/empty-structure.json
  src/app/core/interfaces/goal.ts
  src/app/core/interfaces/strucuture.ts
  src/app/core/services/storage.service.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.scss
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/details/details.component.scss
  src/app/pages/goals/goals.component.html
  src/app/pages/goals/goals.component.scss
  src/app/pages/goals/goals.component.ts
  src/styles.scss
Labels: DASHBOARD, GOALS

#13 Edit/View Toggle Functionality
  src/app/pages/details/details.component.html
  src/app/pages/details/details.component.ts
Labels: NOTES

#14 Goals: Edit, Delete, and Toggle Goals
  src/app/app.module.ts
  src/app/pages/goals/goals.component.html
  src/app/pages/goals/goals.component.scss
  src/app/pages/goals/goals.component.ts
  src/app/shared/images/images.component.html
  src/app/shared/images/images.component.scss
  src/app/shared/images/images.component.spec.ts
  src/app/shared/images/images.component.ts
  src/assets/images/delete.png
  src/assets/images/edit.png
  src/assets/images/gray-check.png
  src/assets/images/green-check.png
  src/styles.scss
Labels: GOALS

#16 Fix
  package.json
Labels: bug

#17 Fix #2
  package.json
Labels: bug

#19 Update favicon.ico
  src/favicon.ico
Labels: enhancement

#25 Create on-pull-request.yml
  .github/workflows/on-pull-request.yml
Labels: enhancement

#30 Update README.md
  README.md
Labels: documentation

#32 LOAD: BUG Load From Buttom
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.spec.ts
  src/app/pages/dashboard/dashboard.component.ts
Labels: bug, DASHBOARD

#33 feat(docker): enable dockerizing of angular app
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement, HACKTOBERFEST-ACCEPTED
